"""Add new relationship

Revision ID: 0182c0980a9c
Revises: 25b93bef5f9b
Create Date: 2020-05-11 15:22:59.667161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0182c0980a9c'
down_revision = '25b93bef5f9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('blog_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'blogs', ['blog_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'blog_id')
    # ### end Alembic commands ###
